version: '3.8'
services:
  csv-processor:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: csv-processor.jar
    image: dsinnovators/ieims-csv-processor:${VERSION:-latest}
    ports:
      - 8104:8080
      - 8073:8010
    environment:
      - CHUNK_SIZE_INTEND_TO_PROCESS=${CHUNK_SIZE_INTEND_TO_PROCESS}
      - INPUT_CSV_FILE_NAME=${INPUT_CSV_FILE_NAME}
      - OUTPUT_CSV_FILE_NAME=${OUTPUT_CSV_FILE_NAME}
    volumes:
      - type: bind
        source: ${INPUT_CSV_PATH}
        target: /storage/inputcsv
      - type: bind
        source: ${OUTPUT_CSV_PATH}
        target: /storage/outputcsv
      - type: bind
        source: ${SOURCE_DIR_PATH}
        target: /storage/srcdir
      - type: bind
        source: ${DESTINATION_DIR_PATH}
        target: /storage/desdir
    deploy:
      resources:
        limits:
          memory: 800M
        reservations:
          memory: 300M
